baseURL = "https://dogdreamson555.github.io/"
title = "dogdreamson555 的博客"
theme = "hugo-theme-stack"
defaultContentLanguage = "zh"
locale = "zh-CN"
hasCJKLanguage = true
timeZone = "Asia/Shanghai"
buildDrafts = false
buildFuture = false
buildExpired = false

[pagination]
  pagerSize = 10

[permalinks]
  post = "/p/:slug/"

[[menus.main]]
  identifier = "home"
  name = "首页"
  pageRef = "/"
  weight = 1
  [menus.main.params]
    icon = "home"
