[highlight]
  noClasses = false
  codeFences = true
  lineNos = true
  lineNumbersInTable = true

[tableOfContents]
  startLevel = 2
  endLevel = 4

[goldmark.renderer]
  unsafe = true

[goldmark.extensions]
  strikethrough = false

[goldmark.extensions.extras.delete]
  enable = true

[goldmark.extensions.extras.subscript]
  enable = true

[goldmark.extensions.extras.superscript]
  enable = true

[goldmark.extensions.passthrough]
  enable = true

  [goldmark.extensions.passthrough.delimiters]
    block = [['\[', '\]'], ['$$', '$$']]
    inline = [['\(', '\)'], ['$', '$']]
